spring.application.name=orchestration-service
server.port=8021

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

ftp.host=127.0.0.1
ftp.port=21
ftp.username=testuser
ftp.password=testpass
ftp.remote-dir=/test

minio.url=http://127.0.0.1:9000
minio.access-key=minioadmin
minio.secret-key=minioadmin123
minio.bucket=ftp-files

test-service.base-url=http://test-service:8022
server.servlet.context-path=/orchestration